name: owwn_coding_challenge
description: OWWN Coding Challenge.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.2"

dependencies:
  dartz: ^0.10.1
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  jwt_io: ^1.1.6
  lumberdash: ^3.0.0
  networking: ^0.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
